name: CI

on: [push]

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Juypter Dependencies
        run: pip install jupyter nbconvert
      - name: Run all notebooks
        run: find . | grep ipynb | xargs -I "{}" jupyter nbconvert --to notebook --execute "{}"